### PR TITLE
Review to finish project

### PR DESCRIPTION
**Pull request by fedgut**
Request Code Review to greenlight project conclusion.

### CODE REVIEW

**Comment by fedgut** [comment]
Passed CSS and HTML validation @ w3.org

**Comment by fedgut** [comment]
# Passed CSS and HTML validation @ w3.org

**Review by stratospherique — COMMENTED** [review]
### Pull request under review by Ahmed Mahfoudh TSE

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great work :clap: . However, You still need to implement some requirements in order to get approval for this project. check below :arrow_down: 

#### Page structure

##### Navigation bar

###### Large version

* [x] It contains main navigation row.

##### Latest Funding section

###### Small version changes

* [x] It aligns 1 articles per row.
> article width is not proportional to viewport width.

##### Footer

* [x] It contains TNW logo with a copyright paragraph.

### That's it Team :relaxed: . When finished implementing the above, kindly resubmit another code review request. :pray:

**Review by Redvanisation — APPROVED** [review]
### Hello @fedgut and @jalasem   🌟

**Great work on this project you fixed all the required changes so I am giving you thumbs up on this one** 👍  

### _Pull request approved you can merge to master and move on to the next project!_ 🚀 

**Good luck guys! 🍀**

**Pull request merged**
